"""Generate deterministic responses from a local or Hugging Face checkpoint."""

from __future__ import annotations

import argparse
from pathlib import Path

import torch

from alignment.data import format_prompt
from alignment.evaluation import append_jsonl, read_records
from alignment.models import load_causal_lm, load_tokenizer


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", required=True, help="HF model ID or saved checkpoint directory")
    parser.add_argument("--prompts", required=True, help="Fixed JSON or JSONL prompt set")
    parser.add_argument("--output", required=True, help="Appendable JSONL output file")
    parser.add_argument("--generator", default=None, help="Human-readable model identity for results")
    parser.add_argument("--dataset", default="alpaca_eval")
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--max-prompt-length", type=int, default=512)
    parser.add_argument(
        "--use-chat-template",
        action="store_true",
        help="Format each user prompt with the tokenizer chat template (for instruct/chat checkpoints)",
    )
    parser.add_argument("--max-new-tokens", type=int, default=256)
    parser.add_argument("--repetition-penalty", type=float, default=1.0)
    parser.add_argument("--no-repeat-ngram-size", type=int, default=0)
    parser.add_argument("--length-penalty", type=float, default=1.0)
    parser.add_argument("--resume", action="store_true", help="Skip IDs already present in output")
    return parser.parse_args()


def main():
    args = parse_args()
    if args.batch_size <= 0:
        raise ValueError("batch-size must be positive")
    device = torch.device(args.device)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested, but no CUDA device is visible.")

    prompts = read_records(args.prompts)
    indexed_prompts = [
        (str(row.get("id", index)), row)
        for index, row in enumerate(prompts)
    ]
    if len({item_id for item_id, _ in indexed_prompts}) != len(indexed_prompts):
        raise ValueError("Prompt IDs must be unique for resumable generation")

    output_path = Path(args.output)
    expected_generator = args.generator or args.model
    if output_path.exists() and not args.resume:
        raise FileExistsError(f"{output_path} already exists; pass --resume or choose a new output path.")

    done = {}
    if output_path.exists():
        for row in read_records(output_path):
            done[str(row.get("id"))] = row
            if row.get("generator") not in (None, expected_generator):
                raise ValueError("Existing output was generated by another model; choose a new output path.")
    pending = [(item_id, row) for item_id, row in indexed_prompts if item_id not in done]
    if not pending:
        print(f"All {len(prompts)} prompts already have outputs in {output_path}.")
        return

    tokenizer = load_tokenizer(args.model)
    tokenizer.padding_side = "left"
    model = load_causal_lm(args.model, dtype=torch.float32).to(device)
    model.config.use_cache = True
    model.eval()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if not output_path.exists():
        output_path.touch()

    for start in range(0, len(pending), args.batch_size):
        indexed_batch = pending[start : start + args.batch_size]
        batch_ids = [item_id for item_id, _ in indexed_batch]
        batch = [row for _, row in indexed_batch]
        instructions = [
            str(row.get("instruction", row.get("prompt", row.get("question", ""))))
            for row in batch
        ]
        if args.use_chat_template:
            formatted = [
                tokenizer.apply_chat_template(
                    [{"role": "user", "content": text}],
                    tokenize=False,
                    add_generation_prompt=True,
                )
                for text in instructions
            ]
        else:
            formatted = [format_prompt(text) for text in instructions]
        encoded = tokenizer(
            formatted,
            add_special_tokens=False,
            padding=True,
            truncation=True,
            max_length=args.max_prompt_length,
            return_tensors="pt",
        )
        encoded = {key: value.to(device) for key, value in encoded.items()}
        input_width = encoded["input_ids"].shape[1]
        generation_args = {
            "max_new_tokens": args.max_new_tokens,
            "do_sample": False,
            "pad_token_id": tokenizer.pad_token_id,
            "eos_token_id": tokenizer.eos_token_id,
            "length_penalty": args.length_penalty,
        }
        if args.repetition_penalty != 1.0:
            generation_args["repetition_penalty"] = args.repetition_penalty
        if args.no_repeat_ngram_size > 0:
            generation_args["no_repeat_ngram_size"] = args.no_repeat_ngram_size

        with torch.no_grad():
            generated = model.generate(**encoded, **generation_args)
        completions = generated[:, input_width:]
        outputs = tokenizer.batch_decode(completions, skip_special_tokens=True)
        for item_id, instruction, output in zip(batch_ids, instructions, outputs):
            append_jsonl(output_path, {
                "id": item_id,
                "instruction": instruction,
                "output": output.strip(),
                "generator": expected_generator,
                "dataset": args.dataset,
                "prompt_format": "chat_template" if args.use_chat_template else "instruction_template",
                "decoding": {
                    "do_sample": False,
                    "temperature": None,
                    "top_p": None,
                    "max_new_tokens": args.max_new_tokens,
                    "repetition_penalty": args.repetition_penalty,
                    "length_penalty": args.length_penalty,
                    "no_repeat_ngram_size": args.no_repeat_ngram_size,
                },
            })
        print(f"Generated {min(start + len(batch), len(pending))}/{len(pending)} new responses.")

    print(f"Saved responses to {output_path}")


if __name__ == "__main__":
    main()